class Config:
    TELEGRAM_BOT_TOKEN = <YOUR TELEGRAM BOT TOKEN HERE>
    OPENAI_API_KEY = <YOUR OPENAPI KEY HERE>
    DEEPGRAM_API_KEY = <YOUR DEEPGRAM KEY HERE>
    TELEGRAM_BASE_URL = <YOUR TELEGRAM BASE URL HERE>